# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpparma_hello_world <- function() {
    .Call(`_la2rcpp_rcpparma_hello_world`)
}

rcpparma_outerproduct <- function(x) {
    .Call(`_la2rcpp_rcpparma_outerproduct`, x)
}

rcpparma_innerproduct <- function(x) {
    .Call(`_la2rcpp_rcpparma_innerproduct`, x)
}

rcpparma_bothproducts <- function(x) {
    .Call(`_la2rcpp_rcpparma_bothproducts`, x)
}

feature <- function(tdata, ran0, brocksize) {
    .Call(`_la2rcpp_feature`, tdata, ran0, brocksize)
}

featurem <- function(tdata, theta, ran0, brocksize, odimno, start) {
    .Call(`_la2rcpp_featurem`, tdata, theta, ran0, brocksize, odimno, start)
}

feature2 <- function(tdata, ran0, brocksize, start, ri) {
    .Call(`_la2rcpp_feature2`, tdata, ran0, brocksize, start, ri)
}

pca <- function(mlimit, traindata0) {
    .Call(`_la2rcpp_pca`, mlimit, traindata0)
}

mtrick <- function(traindata) {
    .Call(`_la2rcpp_mtrick`, traindata)
}

softmax <- function(train_batch_preds) {
    .Call(`_la2rcpp_softmax`, train_batch_preds)
}

update_w <- function(step_size, reg_param, batch_size, blocksz, residue, W_mat, train_batch_X) {
    .Call(`_la2rcpp_update_w`, step_size, reg_param, batch_size, blocksz, residue, W_mat, train_batch_X)
}

mapvec <- function(x, z1, z2) {
    .Call(`_la2rcpp_mapvec`, x, z1, z2)
}

row_find <- function(x, y) {
    .Call(`_la2rcpp_row_find`, x, y)
}

uniqueVec <- function(x) {
    .Call(`_la2rcpp_uniqueVec`, x)
}

